openapi: 3.0.3
info:
  version: 1.0.0
  title: Payment
paths:
  /staff/payment:
    post:
      security:
        - staff: [ ]
      description: 'Creates test payment intent'
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderPaymentDTO'
      responses:
        '200':
          description: Returns payment intent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderPayment'
  /member/checkout-session:
    get:
      security:
        - member: [ ]
      tags:
        - Payment
      description: 'Creates a payment intent'
      responses:
        '200':
          description: Returns payment intent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckoutSessionDTO'
  /member/payment/cancel/{id}:
    post:
      security:
        - member: [ ]
      parameters:
        - in: path
          name: id # Note the name is the same as in the path
          required: true
          schema:
            type: integer
            minimum: 1
      description: 'Cancels a payment'
      tags:
        - Payment
      responses:
        '200':
          description: Returns payment intent
  /member/payment:
    post:
      security:
        - member: [ ]
      description: 'Creates a payment intent'
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderPaymentDTO'
      responses:
        '200':
          description: Returns payment intent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderPayment'
  /stripe/paymentTest:
    post:
      security:
        - member: [ ]
      description: 'Creates test payment intent'
      tags:
        - Stripe
      responses:
        '200':
          description: Returns payment intent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentTestDTO'

  /stripe/constants:
    get:
      description: 'Returns stripe constants'
      tags:
        - Stripe
      responses:
        '200':
          description: Successfully returns the stripe constants
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StripeConstantsDTO'
  /staff/balance/{number}:
    get:
      security:
        - staff: [ ]
      tags:
        - Balance
      parameters:
        - in: path
          name: number
          required: true
          schema:
            type: string
          description: The balance number
      responses:
        '200':
          description: Updated balance dto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
  /member/balance/{number}:
    get:
      security:
        - member: [ ]
      tags:
        - Balance
      parameters:
        - in: path
          name: number
          required: true
          schema:
            type: string
          description: The balance number
      responses:
        '200':
          description: Updated balance dto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
  /staff/balances:
    get:
      summary: Gets a list of balances
      security:
        - staff: [ ]
      tags:
        - Balance
      x-is-paginated: true
      parameters:
        - in: query
          name: personId
          required: false
          schema:
            type: integer
            minimum: 1
          description: The owner of the balance
      responses:
        '200':
          description: Successful fetch of balances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Balance'
    post:
      summary: Updated or creates a balance
      security:
        - staff: [ ]
      tags:
        - Balance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Balance'
      responses:
        '200':
          description: Updated balance dto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
components:
  schemas:
    PaymentTestDTO:
      properties:
        clientSecret:
          type: string
        sessionClientSecret:
          type: string
    StripeConstantsDTO:
      required: [ publicKey, account, apiVersion, locale ]
      properties:
        publicKey:
          type: string
        account:
          type: string
        apiVersion:
          type: string
        locale:
          type: string

    CheckoutSessionDTO:
      type: object
      properties:
        checkoutSecret:
          type: string

    CreateOrderPaymentDTO:
      type: object
      required: [ orderId, payment ]
      properties:
        orderId:
          type: integer
          format: int64
        payment:
          $ref: '#/components/schemas/OrderPayment'
        saveCard:
          type: boolean

    StripeTransactionDTO:
      required: [ id, stripePaymentIntent, transactionAmountCents ]
      properties:
        assignId:
          type: integer
          format: int64
        transactionType:
          $ref: '../shared.yaml#/components/schemas/StripeTransactionType'
        stripePaymentIntent:
          type: string
          readOnly: true
          maxLength: 500
        stripePaymentSecret:
          type: string
          readOnly: true
          maxLength: 500
        transactionAmountCents:
          readOnly: true
          type: integer
          format: int64

    PaymentSource:
      properties:
        id:
          type: integer
          format: int64
        personId:
          $ref: '../existing.yaml#/components/schemas/Person'
        paymentType:
          $ref: '../shared.yaml#/components/schemas/PaymentType'
        stripePaymentSource:
          type: string
          maxLength: 500
        balanceSource:
          $ref: '#/components/schemas/Balance'
        active:
          type: boolean


    OrderPayment:
      required: [ id, orderId, paymentType, paymentSource, paymentAmountCents, paymentStatus ]
      properties:
        id:
          type: integer
          format: int64
        orderId:
          $ref: './order.yaml#/components/schemas/OrderNew'
        paymentType:
          $ref: '../shared.yaml#/components/schemas/PaymentType'
        paymentSource:
          type: string
          maxLength: 100
        paymentServiceChangeCents:
          type: integer
          format: int64
        paymentPaidCents:
          type: integer
          format: int64
        paymentTotalCents:
          type: integer
          format: int64
        paymentRefundedCents:
          type: integer
          format: int64
        paymentToRefundCents:
          type: integer
          format: int64
        paymentStatus:
          $ref: '../shared.yaml#/components/schemas/PaymentStatus'
        paymentDueDate:
          type: string
          format: date-time

    BalanceTransaction:
      required: [ id, balanceId, transactionAmountCents ]
      properties:
        id:
          type: integer
          format: int64
        balanceId:
          $ref: '#/components/schemas/Balance'
        balanceTransactionType:
          $ref: '../shared.yaml#/components/schemas/BalanceTransactionType'
        paymentId:
          $ref: '#/components/schemas/OrderPayment'
        transactionAmountCents:
          type: integer
          format: int64
        purchasableState:
          $ref: '../shared.yaml#/components/schemas/PurchasableState'
        lineItemId:
          $ref: './order.yaml#/components/schemas/LineItem'

    Balance:
      required: [ id, balanceCents, balanceType ]
      properties:
        id:
          type: integer
          format: int64
        balanceAccountNumber:
          writeOnly: true
          type: string
        balanceAccountToken:
          writeOnly: true
          type: string
          maxLength: 64
          minLength: 64
        balanceType:
          $ref: '../shared.yaml#/components/schemas/BalanceType'
        balanceOwner:
          $ref: '../existing.yaml#/components/schemas/Person'

    StripeTransaction:
      required: [ id, stripePaymentIntent, transactionAmountCents ]
      properties:
        id:
          type: integer
          format: int64
        transactionType:
          $ref: '../shared.yaml#/components/schemas/StripeTransactionType'
        stripePaymentIntent:
          type: string
          maxLength: 500
        transactionAmountCents:
          type: integer
          format: int64
        paymentId:
          $ref: '#/components/schemas/OrderPayment'

    CashTransaction:
      required: [ id, cashDrawerId, transactionAmountCents ]
      properties:
        id:
          type: integer
          format: int64
        cashDrawerId:
          allOf:
            - $ref: '../existing.yaml#/components/schemas/CashDrawer'
          x-relation-meta:
            relationType: ONE_TO_MANY
        transactionAmountCents:
          type: integer
          format: int64
        paymentId:
          $ref: '#/components/schemas/OrderPayment'
        cashDrawerChangeId:
          $ref: '#/components/schemas/CashDrawersChange'

    CashDrawersChange:
      required: [ id, changeType, changeAmountCents ]
      properties:
        id:
          type: integer
        changeType:
          type: string
          maxLength: 50
        changeAmountCents:
          type: integer
          format: int64