openapi: 3.0.3
info:
  title: Shared Types
  version: 1.0.0
  description: Shared

paths: {}

components:
  schemas:
    EnumTest:
      type: string
      enum:
        - A
        - B
        - C
        - D
    Boolean:
      type: string
      enum:
        - T
        - F
    RuleType:
      type: string
      enum:
        - 'PARENT_DISCOUNT'
        - 'YOUTH'
        - 'SENIOR'
        - 'VETERAN'
        - 'RENEWAL'
        - '30FULLUPGRADE'
        - '30FULLCOMBO'
        - 'FIXED_PERCENT'
    ItemType:
      type: string
      enum:
        - 'MEMBERSHIP'
        - 'PAID_CLASS'
        - 'DONATION'
        - 'DAMAGE_WAIVER'
        - 'GUEST_PRIVS'
        - 'PRODUCT'
    DiscountType:
      type: string
      enum:
        - 'VARIABLE_AMOUNT'
        - 'VARIABLE_PERCENT'
        - 'FIXED_AMOUNT'
        - 'FIXED_PERCENT'
    OrderStatus:
      type: string
      enum:
        - 'PROCESSED'
        - 'PROCESSING'
        - 'CANCELLED'
    ClassType:
      type: string
      enum:
        - 'JP'
        - 'AP'
    PurchasableState: 
      type: string
      enum:
        - 'PROTO'
        - 'REFUNDED'
        - 'PROCESSED'