openapi: 3.1.3
info:
  title: Shared Types
  version: 1.0.0
  description: Shared

paths: {}

components:
  schemas:
    EnumTest:
      type: string
      enum:
        - A
        - B
        - C
        - D
    Boolean:
      type: string
      enum:
        - T
        - F
    RuleType:
      type: string
      enum:
        - 'PARENT_DISCOUNT'
        - 'YOUTH'
        - 'SENIOR'
        - 'VETERAN'
        - 'RENEWAL'
        - '30FULLUPGRADE'
        - '30FULLCOMBO'
        - 'FIXED_PERCENT'
    ItemType:
      type: string
      enum:
        - 'MEMBERSHIP'
        - 'PAID_CLASS'
        - 'DONATION'
        - 'DAMAGE_WAIVER'
        - 'GUEST_PRIVS'
        - 'PRODUCT'
        - 'CARD'
        - 'GIFT_CARD'
    DiscountType:
      type: string
      enum:
        - 'VARIABLE_AMOUNT'
        - 'VARIABLE_PERCENT'
        - 'VARIABLE'
        - 'FIXED_AMOUNT'
        - 'FIXED_PERCENT'
    OrderSource:
      type: string
      enum:
        - 'IN_PERSON'
        - 'ONLINE'
    OrderStateNew:
      type: string
      enum:
        - 'OPEN'
        - 'PROCESSED'
        - 'PROCESSING'
        - 'REFUNDING'
        - 'REFUNDED'
        - 'PARTIALLY_REFUNDED'
    StockChangeType:
      type: string
      enum:
        - 'PURCHASE'
        - 'RETURN'
        - 'RESTOCK'
        - 'OTHER'
    BalanceType:
      type: string
      enum:
        - 'GIFT_CARD'
        - 'HOUSE_ACCOUNT'
    BalanceTransactionType:
      type: string
      enum:
        - 'GIFT_CARD_PURCHASE'
        - 'GIFT_CARD_LOAD'
        - 'ADD_MANUAL'
        - 'REMOVE_MANUAL'
    ClassTypeEnum:
      type: string
      enum:
        - 'JP'
        - 'AP'
    PurchasableState: 
      type: string
      enum:
        - 'PROTO'
        - 'ACTIVE'
        - 'REVOKED'
        - 'REVOKED_REFUNDED'
        - 'REVOKED_REFUNDED_PARTIALLY'
    PaymentStatus:
      type: string
      enum:
        - 'PENDING'
        - 'SUCCESSFUL'
        - 'FAILED'
        - 'REFUNDED'
        - 'PARTIALLY_REFUNDED'
    PaymentType:
      type: string
      enum:
        - 'CHECK'
        - 'OTHER'
        - 'CASH'
        - 'BALANCE'
        - 'STRIPE'
    StripeTransactionType:
      type: string
      enum:
        - 'CARD_STORED'
        - 'CARD_KEYED'
        - 'CARD_READER'
        - 'WALLET'
    CategoryType:
      type: string
      enum:
        - 'ITEM_TAB'
        - 'ITEM'
        - 'DISCOUNT'
        - 'SHARED'
    PhoneType:
      type: string
      enum:
        - 'WORK'
        - 'HOME'
        - 'CELL'
        - 'MOBILE'
    PersonRelationType:
      type: integer
      x-enum-varnames:
        - ORGANIZATION
        - PARENT_LINKED
        - SPOUSE
        - SIBLING
        - PARENT_UNLINKED
        - EMPLOYER
        - EMERGENCY_CONTACT
        - PURCHASE_RECIPIENT
      enum:
        - 4
        - 2
        - 3
        - 5
        - 6
        - 7
        - 10
        - 11
    PersonTypeEnum:
      type: integer
      x-enum-varnames:
        - JP_INSTRUCTOR
        - ADULT_GUEST
        - ORGANIZATION_CONTACT
        - FRIEND
        - JUNIOR_PARENT
        - ADULT_MEMBER
        - JUNIOR_MEMBER
        - UAP_MEMBER
        - ORGANIZATION
        - EMERGENCY_CONTACT
      enum:
        - 1000
        - 181
        - 21
        - 22
        - 41
        - 1
        - 2
        - 3
        - 4
        - 2000
    ReferralSource:
      type: string
      enum:
        - FRIEND
        - FAMILY
        - SCHOOL
        - MBTA
        - GOOGLE
        - FACEBOOK
        - YOUTUBE
        - WALKING_BY
        - INTERNET
    Gender:
      type: string
      enum:
        - MALE
        - FEMALE
        - NON_BINARY
        - NOT_SPECIFIED
    Ethnicity:
      type: string
      enum:
        - ASIAN
        - BLACK_OR_AFRICAN_AMERICAN
        - HISPANIC_OR_LATINO
        - NATIVE_AMERICAN_OR_ALASKA_NATIVE
        - NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER
        - WHITE
        - MIDDLE_EASTERN_OR_NORTH_AFRICAN
        - OTHER
        - PREFER_NOT_TO_ANSWER
    Language:
      type: string
      enum:
        - ENGLISH
        - AFRIKAANS
        - ALBANIAN
        - AMHARIC
        - ARABIC
        - ARMENIAN
        - ASSAMESE
        - AZERBAIJANI
        - BASQUE
        - BELARUSIAN
        - BENGALI
        - BOSNIAN
        - BULGARIAN
        - BURMESE
        - CATALAN
        - CEBUANO
        - CHICHEWA
        - CHINESE
        - CHINESE_SIMPLIFIED
        - CHINESE_TRADITIONAL
        - CORSICAN
        - CROATIAN
        - CZECH
        - DANISH
        - DUTCH
        - ESPERANTO
        - ESTONIAN
        - FILIPINO
        - FINNISH
        - FRENCH
        - FRISIAN
        - GALICIAN
        - GEORGIAN
        - GERMAN
        - GREEK
        - GUJARATI
        - HAITIAN_CREOLE
        - HAUSA
        - HAWAIIAN
        - HEBREW
        - HINDI
        - HMONG
        - HUNGARIAN
        - ICELANDIC
        - IGBO
        - INDONESIAN
        - IRISH
        - ITALIAN
        - JAPANESE
        - JAVANESE
        - KANNADA
        - KAZAKH
        - KHMER
        - KINYARWANDA
        - KOREAN
        - KURDISH
        - KYRGYZ
        - LAO
        - LATIN
        - LATVIAN
        - LITHUANIAN
        - LUXEMBOURGISH
        - MACEDONIAN
        - MALAGASY
        - MALAY
        - MALAYALAM
        - MALTE
    CountryCode:
      type: string
      x-enum-varnames:
        - AFGHANISTAN
        - ALBANIA
        - ALGERIA
        - ANDORRA
        - ANGOLA
        - ANTIGUA_AND_BARBUDA
        - ARGENTINA
        - ARMENIA
        - AUSTRALIA
        - AUSTRIA
        - AZERBAIJAN
        - BAHAMAS
        - BAHRAIN
        - BANGLADESH
        - BARBADOS
        - BELARUS
        - BELGIUM
        - BELIZE
        - BENIN
        - BHUTAN
        - BOLIVIA
        - BOSNIA_AND_HERZEGOVINA
        - BOTSWANA
        - BRAZIL
        - BRUNEI
        - BULGARIA
        - BURKINA_FASO
        - BURUNDI
        - CAMBODIA
        - CAMEROON
        - CANADA
        - CAPE_VERDE
        - CENTRAL_AFRICAN_REPUBLIC
        - CHAD
        - CHILE
        - CHINA
        - COLOMBIA
        - COMOROS
        - CONGO_REPUBLIC
        - COSTA_RICA
        - COTE_DIVOIRE
        - CROATIA
        - CUBA
        - CYPRUS
        - CZECH_REPUBLIC
        - DEMOCRATIC_REPUBLIC_OF_THE_CONGO
        - DENMARK
        - DJIBOUTI
        - DOMINICA
        - DOMINICAN_REPUBLIC
        - ECUADOR
        - EGYPT
        - EL_SALVADOR
        - EQUATORIAL_GUINEA
        - ERITREA
        - ESTONIA
        - ESWATINI
        - ETHIOPIA
        - FIJI
        - FINLAND
        - FRANCE
        - GABON
        - GAMBIA
        - GEORGIA
        - GERMANY
        - GHANA
        - GREECE
        - GRENADA
        - GUATEMALA
        - GUINEA
        - GUINEA_BISSAU
        - GUYANA
        - HAITI
        - HONDURAS
        - HUNGARY
        - ICELAND
        - INDIA
        - INDONESIA
        - IRAQ
        - IRELAND
        - ISRAEL
        - ITALY
        - JAMAICA
        - JAPAN
        - JORDAN
        - KAZAKHSTAN
        - KENYA
        - KIRIBATI
        - KOSOVO
        - KUWAIT
        - KYRGYZSTAN
        - LAOS
        - LATVIA
        - LEBANON
        - LESOTHO
        - LIBERIA
        - LIBYA
        - LIECHTENSTEIN
        - LITHUANIA
        - LUXEMBOURG
        - MADAGASCAR
        - MALAWI
        - MALAYSIA
        - MALDIVES
        - MALI
        - MALTA
        - MARSHALL_ISLANDS
        - MAURITANIA
        - MAURITIUS
        - MEXICO
        - MICRONESIA
        - MOLDOVA
        - MONACO
        - MONGOLIA
        - MONTENEGRO
        - MOROCCO
        - MOZAMBIQUE
        - MYANMAR
        - NAMIBIA
        - NAURU
        - NEPAL
        - NETHERLANDS
        - NEW_ZEALAND
        - NICARAGUA
        - NIGER
        - NIGERIA
        - NORTH_KOREA
        - NORTH_MACEDONIA
        - NORWAY
        - OMAN
        - PAKISTAN
        - PALAU
        - PANAMA
        - PAPUA_NEW_GUINEA
        - PARAGUAY
        - PERU
        - PHILIPPINES
        - POLAND
        - PORTUGAL
        - QATAR
        - ROMANIA
        - RUSSIA
        - RWANDA
        - SAINT_KITTS_AND_NEVIS
        - SAINT_LUCIA
        - SAINT_VINCENT_AND_THE_GRENADINES
        - SAMOA
        - SAN_MARINO
        - SAO_TOME_AND_PRINCIPE
        - SAUDI_ARABIA
        - SENEGAL
        - SERBIA
        - SEYCHELLES
        - SIERRA_LEONE
        - SINGAPORE
        - SLOVAKIA
        - SLOVENIA
        - SOLOMON_ISLANDS
        - SOMALIA
        - SOUTH_AFRICA
        - SOUTH_KOREA
        - SOUTH_SUDAN
        - SPAIN
        - SRI_LANKA
        - SUDAN
        - SURINAME
        - SWEDEN
        - SWITZERLAND
        - SYRIA
        - TAJIKISTAN
        - TANZANIA
        - THAILAND
        - TIMOR_LESTE
        - TOGO
        - TONGA
        - TRINIDAD_AND_TOBAGO
        - TUNISIA
        - TURKEY
        - TURKMENISTAN
        - TUVALU
        - UGANDA
        - UKRAINE
        - UNITED_ARAB_EMIRATES
        - UNITED_KINGDOM
        - URUGUAY
        - UZBEKISTAN
        - VANUATU
        - VATICAN_CITY
        - VENEZUELA
        - VIETNAM
        - YEMEN
        - ZAMBIA
        - ZIMBABWE
      enum:
        - AF
        - AL
        - DZ
        - AD
        - AO
        - AG
        - AR
        - AM
        - AU
        - AT
        - AZ
        - BS
        - BH
        - BD
        - BB
        - BY
        - BE
        - BZ
        - BJ
        - BT
        - BO
        - BA
        - BW
        - BR
        - BN
        - BG
        - BF
        - BI
        - KH
        - CM
        - CA
        - CV
        - CF
        - TD
        - CL
        - CN
        - CO
        - KM
        - CG
        - CR
        - CI
        - HR
        - CU
        - CY
        - CZ
        - CD
        - DK
        - DJ
        - DM
        - DO
        - EC
        - EG
        - SV
        - GQ
        - ER
        - EE
        - SZ
        - ET
        - FJ
        - FI
        - FR
        - GA
        - GM
        - GE
        - DE
        - GH
        - GR
        - GD
        - GT
        - GN
        - GW
        - GY
        - HT
        - HN
        - HU
        - IS
        - IN
        - ID
        - IQ
        - IE
        - IL
        - IT
        - JM
        - JP
        - JO
        - KZ
        - KE
        - KI
        - XK
        - KW
        - KG
        - LA
        - LV
        - LB
        - LS
        - LR
        - LY
        - LI
        - LT
        - LU
        - MG
        - MW
        - MY
        - MV
        - ML
        - MT
        - MH
        - MR
        - MU
        - MX
        - FM
        - MD
        - MC
        - MN
        - ME
        - MA
        - MZ
        - MM
        - NA
        - NR
        - NP
        - NL
        - NZ
        - NI
        - NE
        - NG
        - KP
        - MK
        - NO
        - OM
        - PK
        - PW
        - PA
        - PG
        - PY
        - PE
        - PH
        - PL
        - PT
        - QA
        - RO
        - RU
        - RW
        - KN
        - LC
        - VC
        - WS
        - SM
        - ST
        - SA
        - SN
        - RS
        - SC
        - SL
        - SG
        - SK
        - SI
        - SB
        - SO
        - ZA
        - KR
        - SS
        - ES
        - LK
        - SD
        - SR
        - SE
        - CH
        - SY
        - TJ
        - TZ
        - TH
        - TL
        - TG
        - TO
        - TT
        - TN
        - TR
        - TM
        - TV
        - UG
        - UA
        - AE
        - GB
        - UY
        - UZ
        - VU
        - VA
        - VE
        - VN
        - YE
        - ZM
        - ZW
    Country:
      type: string
      enum:
        - AFGHANISTAN
        - ALBANIA
        - ALGERIA
        - ANDORRA
        - ANGOLA
        - ANTIGUA_AND_BARBUDA
        - ARGENTINA
        - ARMENIA
        - AUSTRALIA
        - AUSTRIA
        - AZERBAIJAN
        - BAHAMAS
        - BAHRAIN
        - BANGLADESH
        - BARBADOS
        - BELARUS
        - BELGIUM
        - BELIZE
        - BENIN
        - BHUTAN
        - BOLIVIA
        - BOSNIA_AND_HERZEGOVINA
        - BOTSWANA
        - BRAZIL
        - BRUNEI
        - BULGARIA
        - BURKINA_FASO
        - BURUNDI
        - CAMBODIA
        - CAMEROON
        - CANADA
        - CAPE_VERDE
        - CENTRAL_AFRICAN_REPUBLIC
        - CHAD
        - CHILE
        - CHINA
        - COLOMBIA
        - COMOROS
        - CONGO_REPUBLIC
        - COSTA_RICA
        - COTE_DIVOIRE
        - CROATIA
        - CUBA
        - CYPRUS
        - CZECH_REPUBLIC
        - DEMOCRATIC_REPUBLIC_OF_THE_CONGO
        - DENMARK
        - DJIBOUTI
        - DOMINICA
        - DOMINICAN_REPUBLIC
        - ECUADOR
        - EGYPT
        - EL_SALVADOR
        - EQUATORIAL_GUINEA
        - ERITREA
        - ESTONIA
        - ESWATINI
        - ETHIOPIA
        - FIJI
        - FINLAND
        - FRANCE
        - GABON
        - GAMBIA
        - GEORGIA
        - GERMANY
        - GHANA
        - GREECE
        - GRENADA
        - GUATEMALA
        - GUINEA
        - GUINEA_BISSAU
        - GUYANA
        - HAITI
        - HONDURAS
        - HUNGARY
        - ICELAND
        - INDIA
        - INDONESIA
        - IRAQ
        - IRELAND
        - ISRAEL
        - ITALY
        - JAMAICA
        - JAPAN
        - JORDAN
        - KAZAKHSTAN
        - KENYA
        - KIRIBATI
        - KOSOVO
        - KUWAIT
        - KYRGYZSTAN
        - LAOS
        - LATVIA
        - LEBANON
        - LESOTHO
        - LIBERIA
        - LIBYA
        - LIECHTENSTEIN
        - LITHUANIA
        - LUXEMBOURG
        - MADAGASCAR
        - MALAWI
        - MALAYSIA
        - MALDIVES
        - MALI
        - MALTA
        - MARSHALL_ISLANDS
        - MAURITANIA
        - MAURITIUS
        - MEXICO
        - MICRONESIA
        - MOLDOVA
        - MONACO
        - MONGOLIA
        - MONTENEGRO
        - MOROCCO
        - MOZAMBIQUE
        - MYANMAR
        - NAMIBIA
        - NAURU
        - NEPAL
        - NETHERLANDS
        - NEW_ZEALAND
        - NICARAGUA
        - NIGER
        - NIGERIA
        - NORTH_KOREA
        - NORTH_MACEDONIA
        - NORWAY
        - OMAN
        - PAKISTAN
        - PALAU
        - PANAMA
        - PAPUA_NEW_GUINEA
        - PARAGUAY
        - PERU
        - PHILIPPINES
        - POLAND
        - PORTUGAL
        - QATAR
        - ROMANIA
        - RUSSIA
        - RWANDA
        - SAINT_KITTS_AND_NEVIS
        - SAINT_LUCIA
        - SAINT_VINCENT_AND_THE_GRENADINES
        - SAMOA
        - SAN_MARINO
        - SAO_TOME_AND_PRINCIPE
        - SAUDI_ARABIA
        - SENEGAL
        - SERBIA
        - SEYCHELLES
        - SIERRA_LEONE
        - SINGAPORE
        - SLOVAKIA
        - SLOVENIA
        - SOLOMON_ISLANDS
        - SOMALIA
        - SOUTH_AFRICA
        - SOUTH_KOREA
        - SOUTH_SUDAN
        - SPAIN
        - SRI_LANKA
        - SUDAN
        - SURINAME
        - SWEDEN
        - SWITZERLAND
        - SYRIA
        - TAJIKISTAN
        - TANZANIA
        - THAILAND
        - TIMOR_LESTE
        - TOGO
        - TONGA
        - TRINIDAD_AND_TOBAGO
        - TUNISIA
        - TURKEY
        - TURKMENISTAN
        - TUVALU
        - UGANDA
        - UKRAINE
        - UNITED_ARAB_EMIRATES
        - UNITED_KINGDOM
        - URUGUAY
        - UZBEKISTAN
        - VANUATU
        - VATICAN_CITY
        - VENEZUELA
        - VIETNAM
        - YEMEN
        - ZAMBIA
        - ZIMBABWE
    USStateCode:
      type: string
      description: US state and territory codes
      x-enum-varnames:
        - ALABAMA
        - ALASKA
        - ARIZONA
        - ARKANSAS
        - CALIFORNIA
        - COLORADO
        - CONNECTICUT
        - DELAWARE
        - FLORIDA
        - GEORGIA
        - HAWAII
        - IDAHO
        - ILLINOIS
        - INDIANA
        - IOWA
        - KANSAS
        - KENTUCKY
        - LOUISIANA
        - MAINE
        - MARYLAND
        - MASSACHUSETTS
        - MICHIGAN
        - MINNESOTA
        - MISSISSIPPI
        - MISSOURI
        - MONTANA
        - NEBRASKA
        - NEVADA
        - NEW_HAMPSHIRE
        - NEW_JERSEY
        - NEW_MEXICO
        - NEW_YORK
        - NORTH_CAROLINA
        - NORTH_DAKOTA
        - OHIO
        - OKLAHOMA
        - OREGON
        - PENNSYLVANIA
        - RHODE_ISLAND
        - SOUTH_CAROLINA
        - SOUTH_DAKOTA
        - TENNESSEE
        - TEXAS
        - UTAH
        - VERMONT
        - VIRGINIA
        - WASHINGTON
        - WEST_VIRGINIA
        - WISCONSIN
        - WYOMING
        - DISTRICT_OF_COLUMBIA
      enum:
        - AL
        - AK
        - AZ
        - AR
        - CA
        - CO
        - CT
        - DE
        - FL
        - GA
        - HI
        - ID
        - IL
        - IN
        - IA
        - KS
        - KY
        - LA
        - ME
        - MD
        - MA
        - MI
        - MN
        - MS
        - MO
        - MT
        - NE
        - NV
        - NH
        - NJ
        - NM
        - NY
        - NC
        - ND
        - OH
        - OK
        - OR
        - PA
        - RI
        - SC
        - SD
        - TN
        - TX
        - UT
        - VT
        - VA
        - WA
        - WV
        - WI
        - WY
        - DC
    USState:
      type: string
      enum:
        - ALABAMA
        - ALASKA
        - ARIZONA
        - ARKANSAS
        - CALIFORNIA
        - COLORADO
        - CONNECTICUT
        - DELAWARE
        - FLORIDA
        - GEORGIA
        - HAWAII
        - IDAHO
        - ILLINOIS
        - INDIANA
        - IOWA
        - KANSAS
        - KENTUCKY
        - LOUISIANA
        - MAINE
        - MARYLAND
        - MASSACHUSETTS
        - MICHIGAN
        - MINNESOTA
        - MISSISSIPPI
        - MISSOURI
        - MONTANA
        - NEBRASKA
        - NEVADA
        - NEW_HAMPSHIRE
        - NEW_JERSEY
        - NEW_MEXICO
        - NEW_YORK
        - NORTH_CAROLINA
        - NORTH_DAKOTA
        - OHIO
        - OKLAHOMA
        - OREGON
        - PENNSYLVANIA
        - RHODE_ISLAND
        - SOUTH_CAROLINA
        - SOUTH_DAKOTA
        - TENNESSEE
        - TEXAS
        - UTAH
        - VERMONT
        - VIRGINIA
        - WASHINGTON
        - WEST_VIRGINIA
        - WISCONSIN
        - WYOMING
        - DISTRICT_OF_COLUMBIA
    SwimProof:
      type: integer
      x-enum-varnames:
        - YMCA
        - RED_CROSS
        - SCOUTS_BADGE
        - LIFTGUARD_LETTER
      enum:
        - 1
        - 2
        - 3
        - 4