openapi: 3.0.3
info:
  title: Shared Types
  version: 1.0.0
  description: Shared

paths: {}

components:
  schemas:
    EnumTest:
      type: string
      enum:
        - A
        - B
        - C
        - D
    Boolean:
      type: string
      enum:
        - T
        - F
    RuleType:
      type: string
      enum:
        - 'PARENT_DISCOUNT'
        - 'YOUTH'
        - 'SENIOR'
        - 'VETERAN'
        - 'RENEWAL'
        - '30FULLUPGRADE'
        - '30FULLCOMBO'
        - 'FIXED_PERCENT'
    ItemType:
      type: string
      enum:
        - 'MEMBERSHIP'
        - 'PAID_CLASS'
        - 'DONATION'
        - 'DAMAGE_WAIVER'
        - 'GUEST_PRIVS'
        - 'PRODUCT'
        - 'CARD'
        - 'GIFT_CARD'
    DiscountType:
      type: string
      enum:
        - 'VARIABLE_AMOUNT'
        - 'VARIABLE_PERCENT'
        - 'FIXED_AMOUNT'
        - 'FIXED_PERCENT'
    OrderStatusNew:
      type: string
      enum:
        - 'OPEN'
        - 'PROCESSED'
        - 'PROCESSING'
        - 'REFUNDED'
    StockChangeType:
      type: string
      enum:
        - 'PURCHASE'
        - 'RESTOCK'
        - 'OTHER'
    BalanceType:
      type: string
      enum:
        - 'GIFT_CARD'
        - 'HOUSE_ACCOUNT'
    BalanceTransactionType:
      type: string
      enum:
        - 'GIFT_CARD_PURCHASE'
        - 'GIFT_CARD_LOAD'
        - 'ADD_MANUAL'
        - 'REMOVE_MANUAL'
    ClassType:
      type: string
      enum:
        - 'JP'
        - 'AP'
    PurchasableState: 
      type: string
      enum:
        - 'PROTO'
        - 'REFUNDED'
        - 'PURCHASED'
        - 'FREE'
    PaymentStatus:
      type: string
      enum:
        - 'PENDING'
        - 'SUCCESSFUL'
        - 'FAILED'
        - 'REFUNDED'
        - 'PARTIALLY_REFUNDED'
    PaymentType:
      type: string
      enum:
        - 'CHECK'
        - 'OTHER'
        - 'CASH'
        - 'BALANCE'
        - 'STRIPE'
    StripeTransactionType:
      type: string
      enum: 
        - 'CARD_STORED'
        - 'CARD_KEYED'
        - 'CARD_READER'
        - 'WALLET'
